// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://iomnlzeoklcempmljxpc.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvbW5semVva2xjZW1wbWxqeHBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc4NDM5NDgsImV4cCI6MjA4MzQxOTk0OH0.OlMvzOuLSY2O9BPqwG_CsH7YhH6_ogp9BV6orX1BE3M';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

